### PR TITLE
Akhilesh regression testing latest- All the relevant commits for validation of all the brands under regression testing.

### PR DESCRIPTION
**Pull request by AkhileshKhanduri25**
All the relevant commits for validation of all the brands under regression testing are performed as updated the Xpath and required Element IDs in order to successfully complete the execution of the entire regression test suite.

### CODE REVIEW

**Review by ArchanaSaini149 — CHANGES_REQUESTED** [review]
1. Create the pull request for Develop branch always not main branch
2. Please pull develop branch first and resolve the conflicts. Your files are not updated.

**Review by ArchanaSaini149 — CHANGES_REQUESTED** [review]
Please create a pull request for Develop not main.

**Review by ArchanaSaini149 — CHANGES_REQUESTED** [review]
In all the files, you overwrote the develop branch changes. Please keep the changes form develop branch and update your branch.

**Comment by AkhileshKhanduri25** [comment]
The branch is being updated with all latest changes and commits having its base from "develop" instead of "main" now correctly. The review could be completed for the merging without any conflicts in order to complete the regression testing.

**Review by ArchanaSaini149 — CHANGES_REQUESTED** [review]
Still you have overwrite the develop branch. Please update according to Develop branch.

**Comment by AkhileshKhanduri25** [comment]
I had updated all the relevant documentation's keywords, force tags and browser options for all the brancds as per the latest develop branch that could be comapred and reviewed for the resolution of the ticket US-2560.

**Review by AkhileshKhanduri25 — COMMENTED** [review]
The pull request could be reviewed for merging as completed all the relevant commits on all the brands, updated all documentation's defined keywords, force tags and browser options for all the brands as per the latest develop branch that could be compared and reviewed for the resolution of the ticket US-2560.

**Comment by AkhileshKhanduri25** [comment]
I had updated the browser options and force tags for all the brands as well as updated the method for mouse tooltip notification on FN Preference Center page. All the latest relevant commits are made on CommonFunctionality.robot and article files of all brands as per the develop branch that could be reviewed for the resolution of the ticket US-2560.

**Review by ArchanaSaini149 — CHANGES_REQUESTED** [review]
Please update all files.
We have to keep   "${Env}" and remove ${Env} (quotes is the difference)

**Comment by AkhileshKhanduri25** [comment]
I had updated the environemnt keywords as "${Env}", all the browser options and force tags for all the brands as well as updated the method for mouse tooltip notification on FN Preference Center page. All the latest relevant commits are made on CommonFunctionality.robot and article files of all brands as per the develop branch that could be reviewed for the resolution of the ticket US-2560.

**Review by ArchanaSaini149 — CHANGES_REQUESTED** [review]
only this file  is left for changes. Rest all are good
panda-qa/Resources/PageObjects/PENCapabilitiesPage.robot
Please keep: IF  "${Env}" == "prod" and IF  "${Env}" == "dev"

**Review by ArchanaSaini149 — CHANGES_REQUESTED** [review]
Changes required in WSJ_Regression.robot
We need to keep : "${Env}"

**Comment by AkhileshKhanduri25** [comment]
The environment is correctly updated in WSJ_Regression.robot as "${Env}" so the final review comments could be provided along with the approval to merge this pull request.

**Review by ArchanaSaini149 — APPROVED** [review]

**Pull request merged**
